import React from "react";
const details = [
  {
    Year: "2014",
    SubHeading: "10th Board",
    Institution: "Sacred HEart School, Adra, Purulia",
    Marks: "87 Percent",
  },
  {
    Year: "2016",
    SubHeading: "12th Board",
    Institution: "D.A.V Public School, Bokaro",
    Marks: "85 Percent",
  },
  {
    Year: "2020",
    SubHeading: "Bachelor Of Technology(Computer Science)",
    Institution: "Bengal College Of Engineering, Durgapur",
    Marks: "8.5 DGPA",
  },
  {
    Year: "Technical Skills",
    SubHeading: "Skills",
    Institution: [
      "HTML5",
      <br />,
      "CSS3",
      <br />,
      "Javascript",
      <br />,
      "React js",
      <br />,
      "MongoDB",
      <br />,
      "Firebase",
      <br />,
      "Nodejs",
      <br />,
      "REST API",
      <br />,
      "API",
      <br />,
      "Context API",
      <br />,
      "Bootstrap",
      <br />,
      "Material-ui",
      <br />,
      "React Bootstrap",
    ],
  },
  {
    Year: "Trainings",
    SubHeading: "Tranings",
    Institution: [
      "1:Web-Application Development, Udemy, Online.May 2020 - Jun 2020.",
      <br />,
      <br />,
      "2:MongoDBUdemy, Online. May 2020 - Jun 2020.",
      <br />,
      <br />,
      "3:Digital MarketingInternshala, Online.Sep 2019 - Oct 2019.",
      <br />,
      <br />,
      "4:Machine Learning With PythonIndian Cyber Security Service, Kolkata. Jun 2019 - July 2019.",
    ],
  },
  {
    Year: "Extras",
    SubHeading: "Achievements",
    Institution: [
      "1.Secured 1st position in BCET JAM Basketball.",
      <br />,
      <br />,
      "2.Secured 1st position in BCET LIGA Football.",
      <br />,
      <br />,
      "Digital MarketingInternshala, Online.Sep 2019 - Oct 2019",
      <br />,
      <br />,
      "3.Participated in Global Entrepreneurship Summit in IIT Kharagpur.",
    ],
  },
];
export default details;
